---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - openclaw.codeready-toolchain.com
  resources:
  - openclawinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openclaw.codeready-toolchain.com
  resources:
  - openclawinstances/finalizers
  verbs:
  - update
- apiGroups:
  - openclaw.codeready-toolchain.com
  resources:
  - openclawinstances/status
  verbs:
  - get
  - patch
  - update
