apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: CLAW_INSTANCE_NAME-home-pvc
  labels:
    app: claw
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
