apiVersion: openclaw.sandbox.redhat.com/v1alpha1
kind: Claw
metadata:
  name: instance
  namespace: default
spec:
  credentials:
    - name: gemini
      type: apiKey
      secretRef:
        name: gemini-api-key
        key: api-key
      domain: ".googleapis.com"
      apiKey:
        header: x-goog-api-key
